# Generated by Django 5.1 on 2025-01-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0003_alter_women_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="women",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Черновик"), (1, "Опубликованно")], default=0
            ),
        ),
    ]
